name: networkAlignmentAnalysis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - tqdm
